### ISSUE TITLE
Missing dependency for visidata to parse html

### ISSUE THREAD

**Issue by colinmollenhour** [jauderho/dockerfiles#1080]
It appears that "lxml" python package is needed for visidata, it should be added [here](https://github.com/jauderho/dockerfiles/blob/main/visidata/requirements.txt) although I don't know the version numbers that are appropriate. Would you mind adding this dependency? TIA!

**Comment by jauderho** [comment]
Added, although doing so almost doubled the size of the image so I'm not loving that part. 

Let me know if this works for you now.

**Comment by jauderho** [comment]
Thanks. I have a plan to flesh out example commands with both Docker and Docker Compose templates. Pull requests are welcome if you want to help.

**Comment by alneven** [comment]
> -u $(id -u):$(id -g)

thanks @colinmollenhour, that helped me a lot!!!
