### ISSUE TITLE
Embedding thumbnails with yt-dlp

### ISSUE THREAD

**Issue by tauling** [jauderho/dockerfiles#2106]
Hey,

I would like to embed thumbnails in my audio files. `yt-dlp` relies on [mutagen](https://pypi.org/project/mutagen/)  for the thumbnail processing, which seems to be missing in the current build. Could you include it?

Error message when running yt-dlp with `--embed-thumbnail` option:
```
ERROR: Postprocessing: module mutagen was not found. Please install using `python -m pip install mutagen`
```

Best regards

**Comment by jauderho** [comment]
Try now.

**Comment by tauling** [comment]
works. thanks a lot! :slightly_smiling_face:
