### ISSUE TITLE
Remove hardcoded variables, like 'git config user.email "jauderho+update@users.noreply.github.com"' or 'git config user.name "updatebot"'

### ISSUE THREAD

**Issue by MaxPeal** [jauderho/dockerfiles#492]
Remove hard-coded variables, 
without its not possible to fork, update, test and create a PR for an update.
like this:
https://github.com/jauderho/dockerfiles/blob/de11454352d5fbf069a794f102456c3bd9a7f87b/scripts/updateDockerImages.sh#L61-L63
https://github.com/jauderho/dockerfiles/blob/de11454352d5fbf069a794f102456c3bd9a7f87b/scripts/updatePythonDeps.sh#L9-L10

**Comment by jauderho** [comment]
These were removed and are now set in the workflow files.
