### ISSUE TITLE
Make scan.yml build the scan matrix from a file

### ISSUE THREAD

**Issue by jauderho** [jauderho/dockerfiles#494]
It is unwieldy to manually update the matrix in 3 different locations in the workflow. This should be built by reading from a file and building up the matrix.

References:
* https://stackoverflow.com/questions/65056670/is-it-possible-to-have-a-dynamic-strategy-matrix-in-a-workflow-in-github-actions
* https://code.dblock.org/2021/09/03/generating-task-matrix-by-looping-over-repo-files-with-github-actions.html
* https://stackoverflow.com/questions/10234327/convert-bash-ls-output-to-json-array
* https://stackoverflow.com/questions/59977364/github-actions-how-use-strategy-matrix-with-script
* https://www.cynkra.com/blog/2020-12-23-dynamic-gha/

Something along the lines of `cat IMAGES | jq -R -s  'split("\n")[:-1]'` which then produces:

```json
[
  "FiloSottile/age",
  "nakabonne/ali",
  "ansible/ansible",
  "OWASP/amass",
  "jauderho/bl3auto",
  "psf/black",
  "jauderho/cf-warp",
  "cloudflare/cloudflared",
  "coredns/coredns",
  "StackExchange/dnscontrol",
  "DNSCrypt/dnscrypt-proxy",
  "cloudskiff/driftctl",
  "moncho/dry",
  "multiprocessio/dsq",
  "wader/fq",
  "osrg/gobgp",
  "kffl/gocannon",
  "buger/goreplay",
  "juanfont/headscale",
  "nojima/httpie-go",
  "projectdiscovery/httpx",
  "go-acme/lego",
  "fullhunt/log4j-scan",
  "0xInfection/logmepwn",
  "johnkerl/miller",
  "slackhq/nebula",
  "gravitl/netmaker",
  "binwiederhier/ntfy",
  "cube2222/octosql",
  "aramperes/onetun",
  "prettier/prettier",
  "cilium/pwru",
  "rclone/rclone",
  "authzed/spicedb",
  "jtesta/ssh-audit",
  "nabla-c0d3/sslyze",
  "projectdiscovery/subfinder",
  "tailscale/tailscale",
  "hashicorp/terraform",
  "drwetter/testssl.sh",
  "shopify/toxiproxy",
  "tsenart/vegeta",
  "saulpw/visidata",
  "yggdrasil-network/yggdrasil-go",
  "ytdl-org/youtube-dl",
  "yt-dlp/yt-dlp",
  "getzola/zola"
]
```

**Comment by MaxPeal** [comment]
why not get it for the dockerfiles?
https://github.com/jauderho/dockerfiles/pull/495

**Comment by jauderho** [comment]
Commit 9516b2225cac31ece254f53b473e6fdac39a352d completes this.
