### ISSUE TITLE
Simplify workflows

### ISSUE THREAD

**Issue by onedr0p** [jauderho/dockerfiles#54]
Hi 👋🏼 looks like you are doing the same thing the k8s @home community is doing. I just wanted to share this repo to see if you would gain any benefits to the way we do CI for the images we host.

Repo:
https://github.com/k8s-at-home/container-images

Workflow to look for new versions:
https://github.com/k8s-at-home/container-images/blob/main/.github/workflows/schedule.yaml

Workflow to build and push images:
https://github.com/k8s-at-home/container-images/blob/main/.github/workflows/release.yaml

These workflows keep the workflows DRY :)

**Comment by jauderho** [comment]
Thanks for providing this. I'll take a look when I find some time.
