### ISSUE TITLE
Gocannon container image crashes at startup

### ISSUE THREAD

**Issue by kffl** [jauderho/dockerfiles#83]
Since `v0.2.1`, gocannon container image exits just after startup with the following output:
```
standard_init_linux.go:211: exec user process caused "no such file or directory"
```
I've played around with a similar two-stage Dockerfile to the one that is in your repo and it seems that `-buildmode=pie` is the culprit. Below is a Dockerfile, with which I've managed to successfully build gocannon's image without the described issue:
```
FROM golang:1.15 AS builder
WORKDIR /go/src/github.com/kffl/gocannon/
COPY ./ ./
RUN go get ./
RUN CGO_ENABLED=0 GOARCH=amd64 GOOS=linux go build -v -ldflags="-s -w" -o gocannon .

FROM scratch

# SSL CA should be addressed here
WORKDIR /root/
COPY --from=builder /go/src/github.com/kffl/gocannon/gocannon .
ENTRYPOINT ["/root/gocannon"]
CMD ["--help"]
```
The timing of the commit, in which `-buildmode=pie` was added also checks out: https://github.com/jauderho/dockerfiles/commit/f4298f1348bcc1d5d7a5f2ae9e12db357e333df1#diff-9e1d2765235f2c71a0b7315eff5f2d8ceb61386799c550662ee8bb64fe3c0996

**Comment by jauderho** [comment]
So I've run into this error message before. It can be solved one of 2 ways AFAIK. 

1) Revert the -buildmode=pie and retain the ability to use `scratch` as the base image

2) Keep the -buildmode=pie but then we will have to use something like `alpine:3.14` as the base image.

I will note that v1.1.0 seems to have what appears to be very narrow formatting (maybe 20 chars wide) so not sure yet if it is an issue on my side. 

I'm happy to build gocannon either way but I'm leaning towards removing the -buildmode=pie. Thoughts?

**Comment by kffl** [comment]
Thanks for reverting the change. The first option indeed seems reasonable. I've done a quick test and the image using `scratch` without `-buildmode=pie` is half the size of that built on top of `alpine:3.14` with `-buildmode=pie`.

Regarding the output width, printing help it is handled by kingpin, which attempts to read the number of terminal columns from the `COLUMNS` environment variable. If it is not specified (i.e. inside a container), it defaults to 80.

**Comment by jauderho** [comment]
Figured out the problem with the output.

`docker run --rm -it jauderho/gocannon:latest` results in the narrow output but using 
`docker run --rm -i jauderho/gocannon:latest ` resolves the issue.
